#!/usr/bin/env bash

# Set up our own virtual environment.
python -m pip install virtualenv
python -m virtualenv venv
source ./venv/bin/activate

# Install Python packages.
pip install -r requirements.txt

deactivate